// GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// Edit scripts/icons.source.js and re-run it.
//
// Slugs are permanent: a lesson stores the slug, so renaming one silently
// resets every lesson that used it back to the default icon.

export const LESSON_ICONS = [
  // ── Акча жана төлөм
  { slug: 'wallet', label: 'Капчык', group: 'Акча жана төлөм' },
  { slug: 'wallet-cards', label: 'Капчык (карталуу)', group: 'Акча жана төлөм' },
  { slug: 'coins', label: 'Монеталар', group: 'Акча жана төлөм' },
  { slug: 'banknote', label: 'Банкнот', group: 'Акча жана төлөм' },
  { slug: 'credit-card', label: 'Банк картасы', group: 'Акча жана төлөм' },
  { slug: 'hand-coins', label: 'Акча берүү', group: 'Акча жана төлөм' },
  { slug: 'percent', label: 'Пайыз', group: 'Акча жана төлөм' },
  { slug: 'badge-percent', label: 'Арзандатуу', group: 'Акча жана төлөм' },
  { slug: 'circle-dollar-sign', label: 'Доллар', group: 'Акча жана төлөм' },
  { slug: 'badge-dollar-sign', label: 'Баа', group: 'Акча жана төлөм' },
  { slug: 'receipt', label: 'Чек', group: 'Акча жана төлөм' },
  { slug: 'receipt-text', label: 'Кассалык чек', group: 'Акча жана төлөм' },
  { slug: 'arrow-left-right', label: 'Которуу', group: 'Акча жана төлөм' },
  { slug: 'gem', label: 'Асыл таш', group: 'Акча жана төлөм' },

  // ── Банк, үнөмдөө, инвестиция
  { slug: 'piggy-bank', label: 'Чочко-копилка', group: 'Банк, үнөмдөө, инвестиция' },
  { slug: 'landmark', label: 'Банк', group: 'Банк, үнөмдөө, инвестиция' },
  { slug: 'trending-up', label: 'Өсүү', group: 'Банк, үнөмдөө, инвестиция' },
  { slug: 'trending-down', label: 'Түшүү', group: 'Банк, үнөмдөө, инвестиция' },
  { slug: 'chart-pie', label: 'Тегерек диаграмма', group: 'Банк, үнөмдөө, инвестиция' },
  { slug: 'chart-bar', label: 'Устун диаграмма', group: 'Банк, үнөмдөө, инвестиция' },
  { slug: 'chart-line', label: 'Сызык диаграмма', group: 'Банк, үнөмдөө, инвестиция' },
  { slug: 'chart-area', label: 'Аймак диаграмма', group: 'Банк, үнөмдөө, инвестиция' },
  { slug: 'chart-candlestick', label: 'Биржа графиги', group: 'Банк, үнөмдөө, инвестиция' },
  { slug: 'sprout', label: 'Өсүмдүк', group: 'Банк, үнөмдөө, инвестиция' },
  { slug: 'layers', label: 'Портфель', group: 'Банк, үнөмдөө, инвестиция' },
  { slug: 'gauge', label: 'Көрсөткүч', group: 'Банк, үнөмдөө, инвестиция' },

  // ── Пландоо жана убакыт
  { slug: 'calculator', label: 'Эсептегич', group: 'Пландоо жана убакыт' },
  { slug: 'calendar', label: 'Календарь', group: 'Пландоо жана убакыт' },
  { slug: 'calendar-check', label: 'Пландалган күн', group: 'Пландоо жана убакыт' },
  { slug: 'calendar-clock', label: 'Мөөнөт', group: 'Пландоо жана убакыт' },
  { slug: 'clock', label: 'Саат', group: 'Пландоо жана убакыт' },
  { slug: 'timer', label: 'Таймер', group: 'Пландоо жана убакыт' },
  { slug: 'hourglass', label: 'Кум сааты', group: 'Пландоо жана убакыт' },
  { slug: 'target', label: 'Максат', group: 'Пландоо жана убакыт' },
  { slug: 'scale', label: 'Тараза', group: 'Пландоо жана убакыт' },
  { slug: 'list-checks', label: 'Текшерүү тизмеси', group: 'Пландоо жана убакыт' },
  { slug: 'clipboard-list', label: 'Планшет', group: 'Пландоо жана убакыт' },
  { slug: 'notebook-pen', label: 'Дептер', group: 'Пландоо жана убакыт' },

  // ── Коопсуздук жана алдамчылык
  { slug: 'shield-check', label: 'Калкан', group: 'Коопсуздук жана алдамчылык' },
  { slug: 'shield-alert', label: 'Коркунуч', group: 'Коопсуздук жана алдамчылык' },
  { slug: 'key', label: 'Ачкыч', group: 'Коопсуздук жана алдамчылык' },
  { slug: 'lock', label: 'Кулпу', group: 'Коопсуздук жана алдамчылык' },
  { slug: 'unlock', label: 'Ачык кулпу', group: 'Коопсуздук жана алдамчылык' },
  { slug: 'umbrella', label: 'Камсыздандыруу', group: 'Коопсуздук жана алдамчылык' },
  { slug: 'fingerprint', label: 'Манжа изи', group: 'Коопсуздук жана алдамчылык' },
  { slug: 'scan-face', label: 'Жүздү таануу', group: 'Коопсуздук жана алдамчылык' },
  { slug: 'eye-off', label: 'Жашыруу', group: 'Коопсуздук жана алдамчылык' },
  { slug: 'triangle-alert', label: 'Эскертүү', group: 'Коопсуздук жана алдамчылык' },
  { slug: 'octagon-alert', label: 'Токто', group: 'Коопсуздук жана алдамчылык' },
  { slug: 'ban', label: 'Тыюу', group: 'Коопсуздук жана алдамчылык' },
  { slug: 'bug', label: 'Вирус', group: 'Коопсуздук жана алдамчылык' },
  { slug: 'user-x', label: 'Шектүү адам', group: 'Коопсуздук жана алдамчылык' },

  // ── Соода жана турмуш
  { slug: 'home', label: 'Үй', group: 'Соода жана турмуш' },
  { slug: 'house-plus', label: 'Турак жай', group: 'Соода жана турмуш' },
  { slug: 'car', label: 'Унаа', group: 'Соода жана турмуш' },
  { slug: 'shopping-cart', label: 'Себет', group: 'Соода жана турмуш' },
  { slug: 'shopping-bag', label: 'Соода', group: 'Соода жана турмуш' },
  { slug: 'store', label: 'Дүкөн', group: 'Соода жана турмуш' },
  { slug: 'gift', label: 'Белек', group: 'Соода жана турмуш' },
  { slug: 'utensils', label: 'Тамактануу', group: 'Соода жана турмуш' },
  { slug: 'shirt', label: 'Кийим', group: 'Соода жана турмуш' },
  { slug: 'fuel', label: 'Май куюу', group: 'Соода жана турмуш' },
  { slug: 'smartphone', label: 'Телефон', group: 'Соода жана турмуш' },
  { slug: 'ticket', label: 'Билет', group: 'Соода жана турмуш' },

  // ── Иш жана бизнес
  { slug: 'briefcase', label: 'Портфель', group: 'Иш жана бизнес' },
  { slug: 'building', label: 'Кеңсе', group: 'Иш жана бизнес' },
  { slug: 'building-2', label: 'Компания', group: 'Иш жана бизнес' },
  { slug: 'factory', label: 'Өндүрүш', group: 'Иш жана бизнес' },
  { slug: 'handshake', label: 'Келишим', group: 'Иш жана бизнес' },
  { slug: 'hard-hat', label: 'Курулуш', group: 'Иш жана бизнес' },
  { slug: 'users', label: 'Команда', group: 'Иш жана бизнес' },
  { slug: 'user-round-check', label: 'Ишеничтүү', group: 'Иш жана бизнес' },
  { slug: 'network', label: 'Тармак', group: 'Иш жана бизнес' },
  { slug: 'megaphone', label: 'Жарнама', group: 'Иш жана бизнес' },
  { slug: 'contact-round', label: 'Байланыш', group: 'Иш жана бизнес' },

  // ── Билим
  { slug: 'graduation-cap', label: 'Билим', group: 'Билим' },
  { slug: 'book-open', label: 'Ачык китеп', group: 'Билим' },
  { slug: 'book', label: 'Китеп', group: 'Билим' },
  { slug: 'library', label: 'Китепкана', group: 'Билим' },
  { slug: 'school', label: 'Мектеп', group: 'Билим' },
  { slug: 'lightbulb', label: 'Идея', group: 'Билим' },
  { slug: 'brain', label: 'Ой жүгүртүү', group: 'Билим' },
  { slug: 'pencil', label: 'Калем', group: 'Билим' },
  { slug: 'presentation', label: 'Презентация', group: 'Билим' },
  { slug: 'backpack', label: 'Студент', group: 'Билим' },
  { slug: 'microscope', label: 'Изилдөө', group: 'Билим' },

  // ── Мотивация жана сыйлык
  { slug: 'rocket', label: 'Ракета', group: 'Мотивация жана сыйлык' },
  { slug: 'star', label: 'Жылдыз', group: 'Мотивация жана сыйлык' },
  { slug: 'flame', label: 'От', group: 'Мотивация жана сыйлык' },
  { slug: 'trophy', label: 'Кубок', group: 'Мотивация жана сыйлык' },
  { slug: 'medal', label: 'Медаль', group: 'Мотивация жана сыйлык' },
  { slug: 'award', label: 'Сыйлык', group: 'Мотивация жана сыйлык' },
  { slug: 'crown', label: 'Таажы', group: 'Мотивация жана сыйлык' },
  { slug: 'party-popper', label: 'Майрам', group: 'Мотивация жана сыйлык' },
  { slug: 'thumbs-up', label: 'Мыкты', group: 'Мотивация жана сыйлык' },
  { slug: 'heart', label: 'Жүрөк', group: 'Мотивация жана сыйлык' },
  { slug: 'sparkles', label: 'Жаңы', group: 'Мотивация жана сыйлык' },
  { slug: 'zap', label: 'Энергия', group: 'Мотивация жана сыйлык' },
  { slug: 'dumbbell', label: 'Машыгуу', group: 'Мотивация жана сыйлык' },

  // ── Байланыш жана санарип
  { slug: 'mail', label: 'Кат', group: 'Байланыш жана санарип' },
  { slug: 'message-circle', label: 'Билдирүү', group: 'Байланыш жана санарип' },
  { slug: 'bell', label: 'Эскертме', group: 'Байланыш жана санарип' },
  { slug: 'phone', label: 'Чалуу', group: 'Байланыш жана санарип' },
  { slug: 'wifi', label: 'Интернет', group: 'Байланыш жана санарип' },
  { slug: 'qr-code', label: 'QR коду', group: 'Байланыш жана санарип' },
  { slug: 'cloud', label: 'Булут', group: 'Байланыш жана санарип' },
  { slug: 'database', label: 'Маалымат', group: 'Байланыш жана санарип' },
  { slug: 'server', label: 'Сервер', group: 'Байланыш жана санарип' },
  { slug: 'share-2', label: 'Бөлүшүү', group: 'Байланыш жана санарип' },

  // ── Транспорт жана саякат
  { slug: 'plane', label: 'Учак', group: 'Транспорт жана саякат' },
  { slug: 'bus', label: 'Автобус', group: 'Транспорт жана саякат' },
  { slug: 'bike', label: 'Велосипед', group: 'Транспорт жана саякат' },
  { slug: 'map-pin', label: 'Дарек', group: 'Транспорт жана саякат' },
  { slug: 'navigation', label: 'Багыт', group: 'Транспорт жана саякат' },
  { slug: 'compass', label: 'Компас', group: 'Транспорт жана саякат' },
  { slug: 'globe', label: 'Дүйнө', group: 'Транспорт жана саякат' },

  // ── Үй-бүлө, табият
  { slug: 'baby', label: 'Бала', group: 'Үй-бүлө, табият' },
  { slug: 'dog', label: 'Үй жаныбары', group: 'Үй-бүлө, табият' },
  { slug: 'hand-heart', label: 'Кайрымдуулук', group: 'Үй-бүлө, табият' },
  { slug: 'leaf', label: 'Жалбырак', group: 'Үй-бүлө, табият' },
  { slug: 'recycle', label: 'Кайра иштетүү', group: 'Үй-бүлө, табият' },
  { slug: 'sun', label: 'Күн', group: 'Үй-бүлө, табият' },
  { slug: 'droplet', label: 'Суу', group: 'Үй-бүлө, табият' },
  { slug: 'wind', label: 'Шамал', group: 'Үй-бүлө, табият' },
  { slug: 'battery-charging', label: 'Кубаттоо', group: 'Үй-бүлө, табият' },
  { slug: 'tree-deciduous', label: 'Дарак', group: 'Үй-бүлө, табият' },

  // ── Белгилер
  { slug: 'plus', label: 'Кошуу', group: 'Белгилер' },
  { slug: 'minus', label: 'Кемитүү', group: 'Белгилер' },
  { slug: 'check', label: 'Белги', group: 'Белгилер' },
  { slug: 'x', label: 'Жабуу', group: 'Белгилер' },
  { slug: 'info', label: 'Маалымат', group: 'Белгилер' },
  { slug: 'circle-help', label: 'Суроо', group: 'Белгилер' },
  { slug: 'settings', label: 'Жөндөө', group: 'Белгилер' },
  { slug: 'search', label: 'Издөө', group: 'Белгилер' },
  { slug: 'filter', label: 'Чыпка', group: 'Белгилер' },
  { slug: 'arrow-up', label: 'Өйдө', group: 'Белгилер' },
  { slug: 'arrow-down', label: 'Ылдый', group: 'Белгилер' },
  { slug: 'chevron-right', label: 'Кийинки', group: 'Белгилер' },
];

/// Section headings for the admin's picker, in list order.
export const LESSON_ICON_GROUPS = [
  'Акча жана төлөм',
  'Банк, үнөмдөө, инвестиция',
  'Пландоо жана убакыт',
  'Коопсуздук жана алдамчылык',
  'Соода жана турмуш',
  'Иш жана бизнес',
  'Билим',
  'Мотивация жана сыйлык',
  'Байланыш жана санарип',
  'Транспорт жана саякат',
  'Үй-бүлө, табият',
  'Белгилер',
];

/// What the backend validates an authored `icon` against — an unknown slug
/// is stored as null rather than as a value no client can draw
/// (contentStore.js#sanitizeIconSlug).
export const LESSON_ICON_SLUGS = new Set(LESSON_ICONS.map(i => i.slug));
