// scripts/gen-icons.mjs — one icon list in, three clients out.
//
//   node scripts/gen-icons.mjs
//
// Reads scripts/icons.source.js and rewrites:
//   shared/lessonIcons.js              data only — the backend validates against it
//   shared/lessonIconComponents.jsx    slug → lucide component, for the two React bundles
//   mobile/lib/src/core/lucide_svg.dart  slug → SVG string, for Flutter
//
// The point is that the three cannot drift. They used to be maintained by
// hand, and the Flutter half mapped slugs to Material lookalikes — the same
// lesson drew a different picture on each client. Now a slug means exactly
// one drawing everywhere, and adding an icon is one line in one file.
//
// The SVG comes from the copy of lucide already in node_modules (ISC), so
// this fetches nothing.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { ICON_SOURCE } from './icons.source.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ICON_DIR = path.join(ROOT, 'node_modules/lucide-react/dist/esm/icons');

// lucide's file names are not a pure kebab of the export: a trailing digit is
// its own segment (BarChart3 → bar-chart-3), and a few have no rule at all.
const NAME_OVERRIDES = { Home: 'home', Building2: 'building-2', BarChart3: 'bar-chart-3' };
const kebab = (name) =>
  NAME_OVERRIDES[name] ||
  name.replace(/([a-z])([A-Z])/g, '$1-$2').replace(/([A-Za-z])(\d)/g, '$1-$2').toLowerCase();

/// Same defaults lucide-react renders with. `currentColor` stays: it is what
/// lets one string serve every tint on both clients.
const wrap = (body) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" ` +
  `stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${body}</svg>`;

/// lucide stores each icon as an array of ["tag", { attrs }] pairs; rebuild
/// them as SVG source.
function toSvgBody(js) {
  const start = js.indexOf('[', js.indexOf('createLucideIcon'));
  const end = js.lastIndexOf(']);');
  if (start < 0 || end < 0) return null;

  const out = [];
  const elementRe = /\[\s*"([a-z]+)"\s*,\s*\{([\s\S]*?)\}\s*\]/g;
  let el;
  while ((el = elementRe.exec(js.slice(start, end + 1)))) {
    const attrs = [];
    const attrRe = /(["']?)([A-Za-z0-9_-]+)\1\s*:\s*"([^"]*)"/g;
    let a;
    while ((a = attrRe.exec(el[2]))) {
      if (a[2] === 'key') continue; // lucide's React reconciliation key
      attrs.push(`${a[2]}="${a[3]}"`);
    }
    if (attrs.length) out.push(`<${el[1]} ${attrs.join(' ')}/>`);
  }
  return out.length ? out.join('') : null;
}

function svgFor(component, depth = 0) {
  const file = path.join(ICON_DIR, `${kebab(component)}.js`);
  if (!fs.existsSync(file) || depth > 3) return null;
  const js = fs.readFileSync(file, 'utf8');
  // A renamed icon is a one-line re-export (home.js → house.js); follow it.
  const alias = js.match(/export \{ default \} from '\.\/([a-z0-9-]+)\.js'/);
  if (alias) {
    const aliased = path.join(ICON_DIR, `${alias[1]}.js`);
    if (!fs.existsSync(aliased)) return null;
    const body = toSvgBody(fs.readFileSync(aliased, 'utf8'));
    return body ? wrap(body) : null;
  }
  const body = toSvgBody(js);
  return body ? wrap(body) : null;
}

// ── validate before writing anything ──────────────────────────────────────
const seen = new Set();
const problems = [];
for (const icon of ICON_SOURCE) {
  if (seen.has(icon.slug)) problems.push(`duplicate slug: ${icon.slug}`);
  seen.add(icon.slug);
  if (!svgFor(icon.component)) problems.push(`no lucide icon for ${icon.slug} → ${icon.component}`);
}
if (problems.length) {
  console.error('Refusing to generate:\n  ' + problems.join('\n  '));
  process.exit(1);
}

const GENERATED = '// GENERATED by scripts/gen-icons.mjs — do not edit by hand.\n' +
  '// Edit scripts/icons.source.js and re-run it.\n';

// ── 1. the data list, imported by the backend and the admin ───────────────
const groups = [...new Set(ICON_SOURCE.map(i => i.group))];
fs.writeFileSync(
  path.join(ROOT, 'shared/lessonIcons.js'),
  `${GENERATED}//
// Slugs are permanent: a lesson stores the slug, so renaming one silently
// resets every lesson that used it back to the default icon.

export const LESSON_ICONS = [
${groups.map(g =>
  `  // ── ${g}\n` +
  ICON_SOURCE.filter(i => i.group === g)
    .map(i => `  { slug: '${i.slug}', label: '${i.label}', group: '${i.group}' },`)
    .join('\n')
).join('\n\n')}
];

/// Section headings for the admin's picker, in list order.
export const LESSON_ICON_GROUPS = [
${groups.map(g => `  '${g}',`).join('\n')}
];

/// What the backend validates an authored \`icon\` against — an unknown slug
/// is stored as null rather than as a value no client can draw
/// (contentStore.js#sanitizeIconSlug).
export const LESSON_ICON_SLUGS = new Set(LESSON_ICONS.map(i => i.slug));
`
);

// ── 2. the web map — named imports, so the bundler still tree-shakes ──────
const components = [...new Set(ICON_SOURCE.map(i => i.component))].sort();
fs.writeFileSync(
  path.join(ROOT, 'shared/lessonIconComponents.jsx'),
  `${GENERATED}//
// slug → lucide component, for the two React bundles (the learner app and
// the admin panel). The slug list itself lives in lessonIcons.js, which stays
// data-only so the backend can import it.
import {
${components.reduce((lines, c) => {
  const last = lines[lines.length - 1];
  if (last && (last + ` ${c},`).length < 76) lines[lines.length - 1] = `${last} ${c},`;
  else lines.push(`  ${c},`);
  return lines;
}, []).join('\n')}
} from 'lucide-react';

const COMPONENTS = {
${ICON_SOURCE.map(i => `  '${i.slug}': ${i.component},`).join('\n')}
};

/// The component for [slug], or null when unmapped — the caller then draws
/// whatever it was going to draw anyway.
export function lessonIconFor(slug) {
  return (slug && COMPONENTS[slug]) || null;
}
`
);

// ── 3. the Flutter map ────────────────────────────────────────────────────
const NAV = [
  ['nav-learn', 'Home'], ['nav-league', 'Trophy'], ['nav-shop', 'ShoppingBag'],
  ['nav-profile', 'User'], ['nav-settings', 'Settings'],
];
const dartRows = [
  ...ICON_SOURCE.map(i => [i.slug, i.component]),
  ...NAV.filter(([slug]) => !seen.has(slug)),
];
fs.writeFileSync(
  path.join(ROOT, 'mobile/lib/src/core/lucide_svg.dart'),
  `${GENERATED.replace(/^\/\//gm, '//')}//
// The web's icons, as SVG, so the Flutter app draws the same glyphs rather
// than Material lookalikes.
//
// Source: lucide-react ${JSON.parse(fs.readFileSync(path.join(ROOT, 'node_modules/lucide-react/package.json'), 'utf8')).version} (ISC).
// \`currentColor\` is left in place: the renderer swaps it for the colour the
// call site asks for, so one string serves every tint.
library;

const Map<String, String> kLucideSvg = {
${dartRows.map(([slug, comp]) =>
  `  // ${comp}\n  '${slug}': '${svgFor(comp).replace(/'/g, "\\'")}',`
).join('\n')}
};
`
);

console.log(`  ${ICON_SOURCE.length} icons in ${groups.length} groups`);
console.log('  shared/lessonIcons.js');
console.log('  shared/lessonIconComponents.jsx');
console.log(`  mobile/lib/src/core/lucide_svg.dart (${dartRows.length} incl. nav)`);
